name: pluma_env
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - c-compiler
    - cxx-compiler
    # (optional) install some libs via conda for
    - rdkit=2023.03.3
    - ipywidgets
    - jupyter
    - scipy
    - "numpy<2"
    - matplotlib
    - tqdm
    - pandas
    - seaborn
    - msgpack-python
    - pip:
        - torch==2.6
        - lightning==2.5.0.post0
        - wandb==0.18.7
        - py3Dmol
        - torchdata
    
